// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Transaction struct {
	ID          string
	SenderID    string
	RecipientID string
	Amount      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID       string
	Email    string
	Name     string
	Password string
}
